### ISSUE TITLE
Production ready ?

### ISSUE THREAD

**Issue by l1br3** [osofour/web-udp#1]
Hi, did you manage to see if server library was stable enough to be used in production ?

**Comment by 3mcd** [comment]
Hey thanks for asking. This library hasn't been used in production anywhere as far as I know. While I have some basic unit tests and a few E2E tests written, I haven't done a good pass over the app to improve error handling or otherwise improve the robustness of the client or server components. In addition the underlying library (node-webrtc) is notoriously unstable. I'd avoid using it for business-critical apps.

**Comment by l1br3** [comment]
Thank you, the main question was more about the underlying library. Do you use your lib somewhere ?

**Comment by 3mcd** [comment]
Sorry for the late follow-up. I'm using this library in some small personal projects that explore some multiplayer game development concepts. I've only tested the lib up to ~10 concurrent connections. I'm not sure how many it can handle. Check this issue: https://github.com/js-platform/node-webrtc/issues/438
